### ISSUE TITLE
React Native install issues

### ISSUE THREAD

**Issue by justinmakaila** [Clarifai/clarifai-javascript#19] opened 2017-06-21 15:36 UTC
I wrote a little consumer for the `clarifai` API that utilizes this library. Unfortunately, whenever I try to use it, it crashes with a red screen:
![screen shot 2017-06-21 at 11 34 46](https://user-images.githubusercontent.com/1638996/27392814-a55202b0-5675-11e7-8db1-ca7bbf886d72.png)

The client looks like this (currently, which resulted in the red screen, with no implementation):
```
import Clarifai from "clarifai";

const clarifai = new Clarifai.App(
  "client_id",
  "client_secret",
);

export const verifyPhotoBytes = (base64Photo, tags) => {
  console.log("Verifying bytes");
  return Promise.resolve("Hey");
  // return clarifai.inputs
  //   .create({
  //     base64: base64Photo,
  //   })
  //   .then(
  //     response => {
  //       console.log(response);
  //     },
  //     error => {
  //       console.log(error);
  //     },
  //   );
};
```
The crash seems to happen if I try to create a new instance of `Clarifai.App`. I'm on version `2.1.8` using `yarn 0.24.6`

**Comment by justinmakaila** [comment] 2017-06-21 15:41
Update: I removed the creation of the client, and still have the same issue. It seems as if the issue has to do with the actual `import`, not just interacting with the library.

**Comment by justinmakaila** [comment] 2017-06-21 16:06
Update: It seems as if the issue is from the `asap` Promise polyfill utilizing a module called `domain`. The issue is fixed (but not merged!) here: https://github.com/kriskowal/asap/pull/72

In the mean time, I removed `promise` as a dependency and replaced all instances of `require('Promise')` with `global.Promise` in a fork.

**Comment by justinmakaila** [comment] 2017-06-21 16:26
Also, the `main` section in `package.json` points to `dist/index.js` which doesn't exist (i'm also a js noob and could be missing something). I changed it to `src/index.js`

**Comment by jared-clarifai** [comment] 2017-06-21 19:32
Sorry for all the trouble here @justinmakaila. We're actually working on a new version of this and we'll let you know when it's out.

**Comment by neo125874** [comment] 2017-06-29 08:57
@jared-clarifai hi, is this issue fixed? now same error here, version 2.2.0

**Comment by komreezy** [comment] 2017-06-29 19:34
@justinmakaila what's the right way to remove the 'promise' library - just uninstall & unlink are not working for me

**Comment by justinmakaila** [comment] 2017-06-29 22:40
I just replaced all `var Promise = require('promise')` with
`Global.Promise` or whatever. I eventually moved away from this solution
and opted to use a library to build the requests manually; I don't want to
load natively captured images into the js context just for the network. I'm
using `react-native-fetch-blob`.

**Comment by vigzmv** [comment] 2017-07-09 21:59
Same issue.

**Comment by Jonovono** [comment] 2017-07-15 15:35
@jared-clarifai any update when it will be fixed?

**Comment by maxcell** [comment] 2017-07-15 20:21
Howdy all! I have been fiddling around for a bit and I am curious if this will have any impact to what you are doing. I have also tried this on two different node versions: `v6.10.3` and `v8.1.4`. Going from a clean installs on both:

1. Cleaning your cache: `npm cache --force clean`
a. For just in case, be sure to remove your `node_modules` folder.
2. Then `npm install`, you will get all your node modules again
3. Install clarifai `npm install clarifai --save`
a. If in case you are getting babel errors, I would also go `npm install babel-preset-es2015 --save`
4. I also run react native using the `react-native-cli`
a. If you want to install this, go ahead and `npm install react-native-cli`
5. And finally you can run with `react-native run-ios` `react-native`

**Comment by eddiezane** [comment] 2017-08-28 20:35
This appears to happen because `.babelrc` is present in the npm published version. Going to do some research on whether or not we should be ignoring this file when cutting a release.

As an interim fix you can do `rm node_modules/clarifai/.babelrc` and restart the React Native packager.

**Closed** 2017-08-31 18:43 UTC

**Comment by Eyesonly88** [comment] 2017-11-27 00:14
I'm using React Native 0.42 and clarifai 2.5.0 and still get this issue. The main reason I updated clarifai is to use the apiKey auth instead of giving a secret key.

I've tried removing `node_modules` folder and restarting packager multiple times and added the babel dependency as mentioned above but they all didn't work.

**The workaround:**
I forked `promise` lib and updated the version of `asap` from `2.0.3` to `2.0.6`. Right now, i'm depending on my fork for this to work.

**Comment by eddiezane** [comment] 2017-11-27 16:48
@Eyesonly88 @vigzmv I'm unable to reproduce this on a new React Native project.

Steps that succeed:

1. `create-react-native-app clarifai-test`
1. `cd clarifai-test`
1. `yarn add clarifai`
1. Edit `App.js`
```javascript
process.nextTick = setImmediate

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Clarifai from 'clarifai'

const app = new Clarifai.App({
  apiKey: 'CLARIFAI_API_KEY'
})

export default class App extends React.Component {
  componentDidMount() {
    app.models.predict(Clarifai.GENERAL_MODEL, 'https://ulmhawkeyeonline.com/wp-content/uploads/2017/11/puppy-development-300x200.jpg')
      .then(res => console.log(res.outputs[0].data))
      .catch(err => console.error(err))
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
5. `yarn start`
1. Load up Expo and scan qr code (might need to shake device and click `Reload`)
1. See prediction results log out.

Could you please try the above or provide steps to reproduce?

**Comment by vigzmv** [comment] 2017-11-27 17:56
I tried the above, and also tried with ```react-native init```. It worked!
But it is not working with my old [project](https://github.com/vigzmv/what_the_thing), I am getting the same error as in the first comment.
I think this may be related some other dependency, I will investigate more and share my results.

**Comment by NeelShah1998** [comment] 2019-03-31 18:18
clarifai__WEBPACK_IMPORTED_MODULE_7___default.a.app is not a constructor I got this error what should i do?

**Comment by Gagan2601** [comment] 2023-06-15 17:41
what should i do it says "Could not find a declaration file for module 'clarifai' " ??
